name: Build Encrypted AMI with Packer and KMS

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT      

env:
  AWS_REGION: us-east-1 # Set your desired AWS region

jobs:
  create-kms-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
          role-to-assume: arn:aws:iam::874599947932:role/gitaws
          role-session-name: github-actions
          aws-region: us-east-1  

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Create KMS Key
      run: terraform apply -auto-approve
      env:
        TF_IN_AUTOMATION: true

    - name: Get KMS Key ARN
      id: get_kms_key_arn
      run: echo "KMS_KEY_ARN=$(terraform output -raw kms_key_arn)" >> $GITHUB_ENV

  packer:
    runs-on: ubuntu-latest
    needs: create-kms-key
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: arn:aws:iam::874599947932:role/gitaws
        role-session-name: github-actions
        aws-region: us-east-1  

    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "1.10.0" # or "latest"

    - name: Run `packer init`
      id: init
      run: packer init ./jenkinsubuntu.pkr.yaml

    - name: Run `packer validate`
      id: validate
      run: packer validate ./jenkinsubuntu.pkr.yaml

    - name: Run `packer build`
      id: build
      run: packer build ./jenkinsubuntu.pkr.yaml
      env:
        KMS_KEY_ARN: ${{ env.KMS_KEY_ARN }}
